### ISSUE TITLE
Button style does not blend in with theme

### ISSUE THREAD

**Issue by joepie91** [bodhiBit/brackets-boilerplate#1]
Upon installing the plugin, I noticed that the button does appear to conform to the editor theme:

![original_owely20140509-18968-13f1of3](https://cloud.githubusercontent.com/assets/1663259/2932340/2d829aee-d7af-11e3-9a93-ea776ca72de5.png)

In its current state, the button is very distracting. Other 'buttons' in the sidebar appear to be using the `btn-alt-quiet` class - however, those are `<div>`s and not `<button>`s, and thus have a different style. Changing the element to a `<div>` appears to break the dropdown functionality. I'm not sure how this could be fixed.

**Comment by bodhiBit** [comment]
I agree the button stands out in an unfortunate way.. I was originally planning on adding it as a sub-menu to the file listings context menu, but there is no support for sub-menus in Brackets yet, so this was my temporary solution.. As soon as sub-menus are supported, I will remove the button and move all the boilerplates to a convenient sub-menu.. Until then I welcome pull requests that will make the button blend more in.. I'm not sure how to do that though..

**Comment by bodhiBit** [comment]
I have moved the button to the menu bar.. Looks much better now.. :)

**Comment by joepie91** [comment]
Much better indeed :)
